[mqtt]
MQTT_BROKER = "broker.emqx.io"
MQTT_PORT = 1883
QOS_LEVEL = 2
MQTT_TOPIC_SUBSCRIBE = "video/download/request"
MQTT_TOPIC_PUBLISH = "video/download/complete"
MQTT_CLIENT_ID = "video"
DOWNLOAD_DIR = "downloads"
DOWNLOAD_PREFIX_URL=""
MQTT_USERNAME = ""
MQTT_PASSWORD = ""
